### ISSUE TITLE
SCP-106 Teleport issue

### ISSUE THREAD

**Issue by Jasuse** [danx91/SCP-LC#6]
106th may use his teleport mid-air causing him to tp between floor and current positions, causing massive fall damage.

Fix : use this check instead
file weapon_scp_106.lua
line 161
`if self.NextTP > CurTime() or self:GetOwner():GetVelocity().z != 0 then return end`

**Comment by danx91** [comment]
I'm aware of this problem and it's already fixed on dev. Additionally, it will also check for too thin surfaces (sometimes you can achieve the same result on thin metal sheet in SCP 106 room)
