### ISSUE TITLE
SCP SWEPs are weirdly dependent on CW2.0

### ISSUE THREAD

**Issue by Jasuse** [danx91/SCP-LC#7]
Problem:
Removing CW2.0 from addons list causes some SCP`s SWEPs throw client errors

To replicate it, start a new game with unsubscribed or removed CW2.0
Be anyone or SCP-096(for 096`s client error)

![bug1](https://user-images.githubusercontent.com/61157367/119968883-93d38c80-bfb6-11eb-9b70-2a828c1e101e.png)
![bug2](https://user-images.githubusercontent.com/61157367/119968886-946c2300-bfb6-11eb-881f-9783496636a0.png)

Possible fix:
(This bug is really weird, as variables aren`t actually defined in these scopes, but with CW they become so)
Add `local ply = LocalPlayer()` to `PreDrawHalos` in `weapon_scp_24273` on line 724
Use self or define `local wep = self`  in `CalcView` in weapon_scp_096 on line 461

**Comment by danx91** [comment]
Thanks for info, it is clearly a mistake. it was never meant to be dependent on CW 2.0. I just simply forget to add these locals and because of CW it didn't thorw an error.
