### ISSUE TITLE
PreDrop |probably| shouldn`t be used right now in ply:PlayerDropWeapon

### ISSUE THREAD

**Issue by Jasuse** [danx91/SCP-LC#8]
`PreDrop` (as far as I understood) is TTT\`s method to _(usually)_ strict ammo from player and store them in weapon\`s entity. As some bases don\`t define TTT\`s variables on any gamemode _(as ArcCW)_, this may cause some unwanted consequences.
![bug3](https://user-images.githubusercontent.com/61157367/119970507-7b647180-bfb8-11eb-85ce-7fdf5addba1b.png)
`This is what error is thrown, if attempted to pickup ArcCW weapon, if it was dropped with PreDrop() executed`
![arccw_ttt](https://user-images.githubusercontent.com/61157367/119971175-4c023480-bfb9-11eb-9cf2-dcde6b0a8071.png)
![arccw_ttt2](https://user-images.githubusercontent.com/61157367/119971179-4d336180-bfb9-11eb-8768-f504e04e1e72.png)
![arccw_ttt_init](https://user-images.githubusercontent.com/61157367/119971916-3e997a00-bfba-11eb-9392-d968738f4e41.png)

As you can see, `PreDrop` stores ammo, then on `Equip`, it tries to use `ClipMax`(as StoredAmmo is not 0) , which is defined in `TTT_Init`, which only runs in TTT

This also affects TFA base. TFA strips ammo on `PreDrop`, but doesn`t restore them on pickup

**Comment by danx91** [comment]
Thanks for info. I didn't know that PreDrop function is used by TTT (in fact I've never looked in TTT code). In gamemode it's used only for one item so far. Today I'm going to release small patch with fixes, so I'll make sure to rename this function.
